// Auto-extracted from member-shop-details.tsx — behaviour identical.
import { StyleSheet } from 'react-native';

export const styles = StyleSheet.create({
  container: { flex: 1, backgroundColor: '#F3F5F8' },
  loadingContainer: { flex: 1, alignItems: 'center', justifyContent: 'center', padding: 24 },
  loadingText: { marginTop: 12, fontSize: 16, color: '#666', textAlign: 'center' },
  retryButton: {
    marginTop: 20,
    backgroundColor: '#FF8A00',
    paddingHorizontal: 24,
    paddingVertical: 12,
    borderRadius: 8,
    flexDirection: 'row',
    alignItems: 'center',
  },
  retryButtonText: { color: '#FFF', fontSize: 16, fontWeight: '600', marginLeft: 8 },
  header: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    padding: 16,
    backgroundColor: '#FFF',
    borderBottomWidth: 1,
    borderBottomColor: '#EEE',
  },
  backButton: { width: 40, height: 40, justifyContent: 'center' },
  headerTitle: { fontSize: 18, fontWeight: '700', color: '#1A1A1A' },
  headerShareBtn: { width: 40, height: 40, alignItems: 'flex-end', justifyContent: 'center' },
  shopImage: {
    width: '100%',
    height: 250,
    backgroundColor: '#FFF8F0',
    overflow: 'hidden',
  },
  promoHero: { width: '100%', height: 250 },
  shopImageFull: { width: '100%', height: 250, resizeMode: 'cover' },
  shopArrow: {
    position: 'absolute',
    top: '50%',
    width: 32,
    height: 32,
    borderRadius: 16,
    backgroundColor: 'rgba(0,0,0,0.4)',
    alignItems: 'center',
    justifyContent: 'center',
    transform: [{ translateY: -16 }],
  },
  shopArrowLeft: { left: 10 },
  shopArrowRight: { right: 10 },
  heroDots: {
    position: 'absolute',
    bottom: 12,
    left: 0,
    right: 0,
    flexDirection: 'row',
    justifyContent: 'center',
    alignItems: 'center',
    gap: 6,
  },
  heroDot: {
    width: 7,
    height: 7,
    borderRadius: 4,
    backgroundColor: 'rgba(255,255,255,0.55)',
  },
  heroDotActive: {
    width: 18,
    backgroundColor: '#FFFFFF',
  },
  content: { padding: 14, paddingTop: 16 },
  userFlowPressable: { flex: 1 },
  titleCard: {
    backgroundColor: '#FFF',
    borderRadius: 16,
    padding: 16,
    marginBottom: 14,
    shadowColor: '#0F172A',
    shadowOpacity: 0.06,
    shadowRadius: 10,
    shadowOffset: { width: 0, height: 4 },
    elevation: 2,
  },
  titleRow: {
    flexDirection: 'row',
    alignItems: 'flex-start',
    justifyContent: 'space-between',
    gap: 10,
  },
  nameRow: { flex: 1, flexDirection: 'row', alignItems: 'center', flexWrap: 'wrap', gap: 6 },
  shopName: { fontSize: 20, fontWeight: '800', color: '#1A1A1A', flexShrink: 1 },
  verifiedIcon: { marginTop: 1 },
  shopTagline: { fontSize: 13, color: '#6B7280', marginTop: 4, lineHeight: 18, paddingRight: 90 },
  badge: { paddingHorizontal: 12, paddingVertical: 5, borderRadius: 999, borderWidth: 1, borderColor: 'rgba(0,0,0,0.04)' },
  badgeText: { fontSize: 12, fontWeight: '700' },
  descriptionCard: {
    backgroundColor: '#FFF',
    borderRadius: 16,
    padding: 16,
    marginBottom: 14,
    shadowColor: '#0F172A',
    shadowOpacity: 0.05,
    shadowRadius: 8,
    shadowOffset: { width: 0, height: 3 },
    elevation: 2,
  },
  descriptionTitle: { fontSize: 12, fontWeight: '700', color: '#8A94A6', letterSpacing: 1.1, marginBottom: 12 },
  descriptionCallout: {
    flexDirection: 'row',
    alignItems: 'flex-start',
    gap: 10,
    backgroundColor: '#EEF9F1',
    borderWidth: 1,
    borderColor: '#C9EBD3',
    borderRadius: 12,
    padding: 12,
  },
  descriptionIcon: {
    width: 26,
    height: 26,
    borderRadius: 13,
    backgroundColor: '#D7F0DE',
    alignItems: 'center',
    justifyContent: 'center',
    marginTop: 1,
  },
  descriptionText: { flex: 1, fontSize: 14, color: '#1F2937', lineHeight: 21, fontWeight: '500' },
  infoCard: {
    backgroundColor: '#FFF',
    borderRadius: 16,
    paddingHorizontal: 16,
    paddingVertical: 6,
    marginBottom: 14,
    shadowColor: '#0F172A',
    shadowOpacity: 0.05,
    shadowRadius: 8,
    shadowOffset: { width: 0, height: 3 },
    elevation: 2,
  },
  liveGpsChip: { backgroundColor: '#EAF2FF', borderRadius: 999, paddingHorizontal: 10, paddingVertical: 4 },
  liveGpsText: { fontSize: 11, fontWeight: '700', color: '#2F80ED' },
  callBtn: {
    width: 32,
    height: 32,
    borderRadius: 16,
    backgroundColor: '#E8F5E9',
    alignItems: 'center',
    justifyContent: 'center',
  },
  openingHoursHeader: { flexDirection: 'row', alignItems: 'center', gap: 8, paddingTop: 10, marginBottom: 12 },
  openingHoursTitle: { fontSize: 16, fontWeight: '700', color: '#1A1A1A' },
  hoursGrid: { flexDirection: 'row', flexWrap: 'wrap', gap: 10, paddingBottom: 10 },
  hoursTile: {
    width: '48%',
    flexGrow: 1,
    backgroundColor: '#F6F8FB',
    borderRadius: 12,
    padding: 12,
  },
  hoursTileLabelRow: { flexDirection: 'row', alignItems: 'center', gap: 6, marginBottom: 6 },
  hoursDot: { width: 7, height: 7, borderRadius: 4 },
  hoursLabel: { fontSize: 12, color: '#8A94A6', fontWeight: '500' },
  hoursValue: { fontSize: 14, fontWeight: '700', color: '#1A1A1A' },
  savingsCard: {
    backgroundColor: '#EEF9F1',
    borderWidth: 1,
    borderColor: '#BFE6CC',
    borderRadius: 16,
    padding: 14,
    alignItems: 'center',
    marginBottom: 6,
  },
  savingsImageWrap: { width: '100%', marginBottom: 14, borderRadius: 12, overflow: 'hidden' },
  savingsImage: { width: '100%', aspectRatio: 16 / 9, backgroundColor: '#DDEFE2' },
  savingsTag: {
    position: 'absolute',
    left: 12,
    bottom: 12,
    backgroundColor: '#FF8A00',
    borderRadius: 6,
    paddingHorizontal: 10,
    paddingVertical: 5,
  },
  savingsTagText: { color: '#FFF', fontSize: 11, fontWeight: '800', letterSpacing: 0.8 },
  savingsIconCircle: {
    width: 44,
    height: 44,
    borderRadius: 22,
    backgroundColor: '#FF8A00',
    alignItems: 'center',
    justifyContent: 'center',
    marginTop: 2,
  },
  savingsTitle: { fontSize: 18, fontWeight: '800', color: '#1A1A1A', marginTop: 10 },
  savingsText: { fontSize: 13, color: '#374151', textAlign: 'center', marginTop: 6, lineHeight: 19, paddingHorizontal: 8 },
  savingsChipsRow: { flexDirection: 'row', flexWrap: 'wrap', justifyContent: 'center', gap: 8, marginTop: 14 },
  savingsValidChip: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 6,
    backgroundColor: '#D7F0DE',
    borderRadius: 999,
    paddingHorizontal: 12,
    paddingVertical: 6,
  },
  savingsValidTill: { fontSize: 12, color: '#1B5E20', fontWeight: '700' },
  savingsCodeChip: {
    backgroundColor: '#FFF',
    borderWidth: 1,
    borderColor: '#D1D5DB',
    borderRadius: 999,
    paddingHorizontal: 12,
    paddingVertical: 6,
  },
  savingsCodeText: { fontSize: 12, color: '#1A1A1A', fontWeight: '700', letterSpacing: 0.6 },
  bottomButtons: {
    flexDirection: 'row',
    paddingHorizontal: 14,
    paddingVertical: 12,
    backgroundColor: '#FFF',
    borderTopWidth: 1,
    borderTopColor: '#EEF0F3',
    gap: 12,
  },
  navigateBtn: {
    flex: 1,
    backgroundColor: '#29B6F6',
    borderRadius: 14,
    paddingVertical: 15,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    shadowColor: '#29B6F6',
    shadowOpacity: 0.3,
    shadowRadius: 8,
    shadowOffset: { width: 0, height: 4 },
    elevation: 3,
  },
  navigateBtnText: { color: '#FFF', fontSize: 15, fontWeight: '800', marginLeft: 8 },
  payBtn: {
    flex: 1,
    backgroundColor: '#FF8A00',
    borderRadius: 14,
    paddingVertical: 15,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    shadowColor: '#FF8A00',
    shadowOpacity: 0.3,
    shadowRadius: 8,
    shadowOffset: { width: 0, height: 4 },
    elevation: 3,
  },
  payBtnText: { color: '#FFF', fontSize: 15, fontWeight: '800', marginLeft: 8 },
  modalContainer: {
    flex: 1,
    backgroundColor: 'rgba(0,0,0,0.5)',
    justifyContent: 'flex-end',
  },
  modalContent: {
    backgroundColor: '#FFFFFF',
    borderTopLeftRadius: 24,
    borderTopRightRadius: 24,
    padding: 24,
  },
  modalTitle: {
    fontSize: 20,
    fontWeight: 'bold',
    color: '#1A1A1A',
    marginBottom: 24,
    textAlign: 'center',
  },
  modalButton: {
    flexDirection: 'row',
    alignItems: 'center',
    backgroundColor: '#FFF3E0',
    borderRadius: 12,
    padding: 16,
    marginBottom: 12,
  },
  modalButtonText: {
    fontSize: 16,
    fontWeight: '600',
    color: '#FF8A00',
    marginLeft: 12,
  },
  modalCancelButton: {
    padding: 16,
    alignItems: 'center',
  },
  modalCancelText: {
    fontSize: 16,
    color: '#666666',
  },
  fullscreenOverlay: {
    flex: 1,
    backgroundColor: 'rgba(0,0,0,0.95)',
    justifyContent: 'center',
    alignItems: 'center',
  },
  fullscreenCloseBtn: {
    position: 'absolute',
    top: 50,
    right: 20,
    zIndex: 10,
  },
  fullscreenImage: {
    width: '100%',
    height: '80%',
  },

  // ================= ORDER FEATURE STYLES (Blinkit-style) =================
  orderBtn: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    gap: 8,
    backgroundColor: '#FF8A00',
    borderRadius: 14,
    paddingVertical: 15,
    marginTop: 16,
    shadowColor: '#FF8A00',
    shadowOpacity: 0.3,
    shadowRadius: 8,
    shadowOffset: { width: 0, height: 4 },
    elevation: 3,
  },
  orderBtnText: {
    color: '#FFFFFF',
    fontSize: 16,
    fontWeight: '700',
  },
  orderModalOverlay: {
    flex: 1,
    backgroundColor: 'rgba(0,0,0,0.5)',
    justifyContent: 'flex-end',
  },
  orderModalCard: {
    backgroundColor: '#FFFFFF',
    borderTopLeftRadius: 20,
    borderTopRightRadius: 20,
    height: '90%',
    overflow: 'hidden',
  },
  orderModalHeader: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    paddingHorizontal: 20,
    paddingTop: 16,
    paddingBottom: 12,
    borderBottomWidth: 1,
    borderBottomColor: '#F0F0F0',
    backgroundColor: '#FFFFFF',
  },
  orderModalTitle: {
    fontSize: 18,
    fontWeight: '800',
    color: '#1A1A1A',
  },
  orderModalSubtitle: {
    fontSize: 12,
    color: '#666',
    marginTop: 2,
  },
  orderModalCloseBtn: {
    width: 34,
    height: 34,
    borderRadius: 17,
    backgroundColor: '#F5F5F5',
    alignItems: 'center',
    justifyContent: 'center',
  },
  orderModalScroll: {
    flex: 1,
    backgroundColor: '#FAFAFA',
  },
  orderModalScrollContent: {
    paddingHorizontal: 16,
    paddingTop: 12,
    paddingBottom: 24,
  },
  orderSectionLabel: {
    fontSize: 15,
    fontWeight: '800',
    color: '#1A1A1A',
    marginBottom: 12,
    marginTop: 4,
  },

  // Search bar inside modal
  productSearchWrap: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 8,
    backgroundColor: '#FFFFFF',
    borderRadius: 10,
    borderWidth: 1,
    borderColor: '#E5E5E5',
    paddingHorizontal: 12,
    paddingVertical: 4,
    marginBottom: 12,
  },
  productSearchInput: {
    flex: 1,
    fontSize: 14,
    color: '#1A1A1A',
    paddingVertical: 8,
  },

  // Grid of product cards — exactly 3 columns on every device (percentage-only sizing).
  productsGrid: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    justifyContent: 'flex-start',
    marginHorizontal: -4,
  },
  productCard: {
    width: '33.3333%',
    paddingHorizontal: 4,
    marginBottom: 10,
  },
  productCardInner: {
    backgroundColor: '#FFFFFF',
    borderRadius: 12,
    padding: 8,
    borderWidth: 1,
    borderColor: '#EDEDED',
  },
  productImageWrap: {
    width: '100%',
    aspectRatio: 4 / 3,
    borderRadius: 10,
    alignItems: 'center',
    justifyContent: 'center',
    marginBottom: 8,
  },
  productCardName: {
    fontSize: 12,
    fontWeight: '700',
    color: '#1A1A1A',
    marginBottom: 4,
    minHeight: 30,
  },
  unitChip: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    backgroundColor: '#F5F5F5',
    borderRadius: 6,
    paddingHorizontal: 6,
    paddingVertical: 4,
    marginBottom: 8,
    borderWidth: 1,
    borderColor: '#E5E5E5',
    position: 'relative',
  },
  unitChipText: {
    fontSize: 11,
    color: '#333',
    fontWeight: '600',
    flex: 1,
    marginRight: 4,
  },
  unitDropdown: {
    backgroundColor: '#FFFFFF',
    borderRadius: 6,
    borderWidth: 1,
    borderColor: '#E5E5E5',
    marginBottom: 8,
    marginTop: -4,
    overflow: 'hidden',
    position: 'absolute',
    top: 22,
    width: '70%',
  },
  unitOption: {
    paddingHorizontal: 8,
    paddingVertical: 6,
    borderBottomWidth: 1,
    borderBottomColor: '#F5F5F5',
  },
  unitOptionSelected: {
    backgroundColor: '#FFF3E0',
  },
  unitOptionText: {
    fontSize: 11,
    color: '#333',
    fontWeight: '500',
  },
  unitOptionTextSelected: {
    color: '#FF8A00',
    fontWeight: '700',
  },
  addBtn: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    gap: 2,
    borderWidth: 1.5,
    borderRadius: 8,
    paddingVertical: 6,
    backgroundColor: '#FFFFFF',
  },
  addBtnText: {
    fontSize: 12,
    fontWeight: '800',
  },
  qtyControl: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    borderRadius: 8,
    paddingVertical: 4,
    paddingHorizontal: 4,
  },
  qtyBtn: {
    width: 22,
    height: 22,
    borderRadius: 5,
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: 'rgba(255,255,255,0.15)',
  },
  qtyValue: {
    fontSize: 13,
    fontWeight: '800',
    color: '#FFFFFF',
    minWidth: 18,
    textAlign: 'center',
  },

  orderProductsLoading: {
    alignItems: 'center',
    paddingVertical: 40,
  },
  orderProductsLoadingText: {
    marginTop: 8,
    color: '#666',
    fontSize: 13,
  },
  orderProductsEmpty: {
    alignItems: 'center',
    padding: 24,
    backgroundColor: '#FFFFFF',
    borderRadius: 10,
    borderWidth: 1,
    borderColor: '#EEE',
  },
  orderProductsEmptyText: {
    marginTop: 8,
    color: '#888',
    fontSize: 13,
    textAlign: 'center',
    marginBottom: 12,
  },
  retryBtn: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 6,
    backgroundColor: '#FF8A00',
    borderRadius: 8,
    paddingHorizontal: 14,
    paddingVertical: 8,
  },
  retryBtnText: {
    color: '#FFFFFF',
    fontWeight: '700',
    fontSize: 13,
  },

  // Fixed bottom footer
  orderModalFooter: {
    padding: 16,
    borderTopWidth: 1,
    borderTopColor: '#EEE',
    backgroundColor: '#FFFFFF',
  },
  orderFooterLabel: {
    fontSize: 13,
    fontWeight: '700',
    color: '#666',
    marginBottom: 8,
  },
  orderTypeRow: {
    flexDirection: 'row',
    gap: 12,
    marginBottom: 12,
  },
  orderTypeChip: {
    flex: 1,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    gap: 6,
    paddingVertical: 10,
    borderRadius: 10,
    borderWidth: 1,
    borderColor: '#FF8A00',
    backgroundColor: '#FFF8F0',
  },
  orderTypeChipActive: {
    backgroundColor: '#FF8A00',
    borderColor: '#FF8A00',
  },
  orderTypeChipText: {
    color: '#FF8A00',
    fontWeight: '700',
    fontSize: 14,
  },
  orderTypeChipTextActive: {
    color: '#FFFFFF',
  },
  orderErrorBanner: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 8,
    backgroundColor: '#FDECEA',
    borderRadius: 10,
    paddingVertical: 8,
    paddingHorizontal: 12,
    borderWidth: 1,
    borderColor: '#F5C2C0',
    marginBottom: 8,
  },
  orderErrorText: {
    color: '#D32F2F',
    fontSize: 12,
    fontWeight: '600',
    flex: 1,
  },
  orderSubmitBtn: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    gap: 10,
    backgroundColor: '#FF8A00',
    borderRadius: 12,
    paddingVertical: 14,
    marginBottom: 32,
  },
  orderSubmitBtnDisabled: {
    backgroundColor: '#CCCCCC',
  },
  orderSubmitBtnText: {
    color: '#FFFFFF',
    fontSize: 16,
    fontWeight: '800',
  },
  submitBadge: {
    backgroundColor: 'rgba(255,255,255,0.25)',
    borderRadius: 999,
    paddingHorizontal: 10,
    paddingVertical: 2,
  },
  submitBadgeText: {
    color: '#FFFFFF',
    fontSize: 12,
    fontWeight: '700',
  },

  // Floating post-order toast on shop-details page
  orderToast: {
    position: 'absolute',
    top: 80,
    left: 16,
    right: 16,
    zIndex: 9999,
    borderRadius: 12,
    borderWidth: 1,
    shadowColor: '#000',
    shadowOpacity: 0.12,
    shadowRadius: 12,
    shadowOffset: { width: 0, height: 4 },
    elevation: 8,
  },
  orderToastSuccess: {
    backgroundColor: '#E8F5E9',
    borderColor: '#B7E1BF',
  },
  orderToastError: {
    backgroundColor: '#FDECEA',
    borderColor: '#F5C2C0',
  },
  orderToastInner: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 10,
    padding: 12,
  },
  orderToastText: {
    flex: 1,
    fontSize: 14,
    fontWeight: '700',
  },
});
