// Auto-extracted from register-merchant.tsx — behaviour identical.
import { StyleSheet } from 'react-native';

export const styles = StyleSheet.create({
  container: { flex: 1, backgroundColor: '#F5F5F5' },
  header: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    padding: 16,
    backgroundColor: '#FFFFFF',
    borderBottomWidth: 1,
    borderBottomColor: '#EEEEEE',
  },
  backButton: {
    width: 40,
    height: 40,
    justifyContent: 'center',
  },
  headerTitle: {
    fontSize: 18,
    fontWeight: '600',
    color: '#1A1A1A',
  },
  placeholder: {
    width: 40,
  },
  content: { padding: 16 },
  formGroup: { marginBottom: 16 },
  label: { fontSize: 14, fontWeight: '600', marginBottom: 6 },
  slug:{
    fontSize: 12,
    color: '#666',
  },
  input: {
    backgroundColor: '#FFF',
    borderWidth: 1,
    borderColor: '#DDD',
    borderRadius: 8,
    padding: 12,
  },
  inputError: {
    borderColor: '#FF3B30',
  },
  textArea: {
    backgroundColor: '#FFF',
    borderWidth: 1,
    borderColor: '#DDD',
    borderRadius: 8,
    padding: 12,
    minHeight: 80,
  },
  row: { flexDirection: 'row', alignItems: 'center', marginVertical: 6 },
  rowText: { marginLeft: 8 },
  submitBtn: {
    backgroundColor: '#FF8A00',
    padding: 14,
    borderRadius: 8,
    marginTop: 24,
    alignItems: 'center',
  },
  submitBtnDisabled: {
    backgroundColor: '#CCCCCC',
  },

  selectProductsBtn: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    gap: 8,
    paddingVertical: 12,
    marginTop: 12,
    borderRadius: 10,
    borderWidth: 1,
    borderColor: '#FF8A00',
    backgroundColor: '#FFF8F0',
  },
  selectProductsBtnText: {
    fontSize: 15,
    fontWeight: '600',
    color: '#FF8A00',
  },
  productCountBadge: {
    backgroundColor: '#FF8A00',
    borderRadius: 10,
    minWidth: 20,
    height: 20,
    alignItems: 'center',
    justifyContent: 'center',
    paddingHorizontal: 6,
  },
  productCountText: {
    color: '#FFF',
    fontSize: 11,
    fontWeight: '700',
  },
  selectedProductsContainer: {
    marginVertical: 12,
    padding: 12,
    backgroundColor: '#FFF',
    borderRadius: 10,
    borderWidth: 1,
    borderColor: '#EEE',
  },
  selectedProductsTitle: {
    fontSize: 14,
    fontWeight: '700',
    color: '#333',
    marginBottom: 8,
  },
  selectedProductsList: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    gap: 8,
  },
  selectedProductChip: {
    flexDirection: 'row',
    alignItems: 'center',
    backgroundColor: '#FFF3E0',
    borderRadius: 16,
    paddingVertical: 6,
    paddingLeft: 12,
    paddingRight: 6,
    gap: 4,
  },
  selectedProductChipText: {
    fontSize: 13,
    color: '#333',
    fontWeight: '500',
  },
  removeProductBtn: {
    padding: 2,
  },
  submitText: { color: '#FFF', fontWeight: '600' },
  helperText: {
    fontSize: 12,
    color: '#777',
    marginTop: 4,
    fontStyle: 'italic',
  },
  labelRow: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    marginBottom: 4,
  },
  charCounter: {
    fontSize: 12,
    color: '#888',
    fontWeight: '600',
  },
  charCounterMax: {
    color: '#D32F2F',
  },
  disabledInput: {
    backgroundColor: '#F5F5F5',
    color: '#666666',
  },
  errorText: {
    fontSize: 12,
    color: 'red',
    marginTop: 4,
  },
  imageActions: {
    flexDirection: 'row',
    gap: 12,
    marginBottom: 12,
  },
  imageButton: {
    flex: 1,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: '#FFF3E0',
    borderRadius: 8,
    paddingVertical: 10,
    borderWidth: 1,
    borderColor: '#FFD9B3',
  },
  imageButtonText: {
    marginLeft: 8,
    color: '#FF8A00',
    fontWeight: '600',
  },
  imagesPreviewContainer: {
    overflow: 'visible',
    marginTop: 8,
  },
  imagesPreview: {
    paddingTop: 12,
    paddingBottom: 4,
    paddingLeft: 4,
  },
  imagesPreviewContent: {
    paddingRight: 16,
  },
  imageThumbContainer: {
    position: 'relative',
    marginRight: 16,
  },
  imageThumb: {
    width: 80,
    height: 80,
    borderRadius: 8,
    backgroundColor: '#EEE',
  },
  removeImageButton: {
    position: 'absolute',
    top: -10,
    right: -10,
    backgroundColor: '#FFFFFF',
    borderRadius: 14,
    width: 28,
    height: 28,
    alignItems: 'center',
    justifyContent: 'center',
    elevation: 3,
    shadowColor: '#000',
    shadowOpacity: 0.25,
    shadowRadius: 3,
    shadowOffset: { width: 0, height: 1 },
    zIndex: 10,
  },
  imageCountText: {
    marginTop: 8,
    fontSize: 13,
    color: '#666',
    fontStyle: 'italic',
  },
  locationButton: {
    flexDirection: 'row',
    alignItems: 'center',
    backgroundColor: '#FFF',
    borderWidth: 1,
    borderColor: '#DDD',
    borderRadius: 8,
    padding: 12,
  },
  locationButtonText: {
    marginLeft: 8,
    fontSize: 14,
    color: '#333',
  },
  locationDisplay: {
    backgroundColor: '#FFF',
    borderWidth: 1,
    borderColor: '#E0E0E0',
    borderRadius: 10,
    padding: 12,
  },
  locationCoords: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 8,
    marginBottom: 10,
  },
  locationCoordsText: {
    fontSize: 14,
    fontWeight: '600',
    color: '#1A1A1A',
  },
  changeLocationBtn: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    gap: 6,
    paddingVertical: 10,
    borderRadius: 8,
    borderWidth: 1,
    borderColor: '#FF8A00',
    backgroundColor: '#FFF8F0',
  },
  changeLocationText: {
    fontSize: 14,
    fontWeight: '600',
    color: '#FF8A00',
  },

  categoryGrid: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    justifyContent: 'space-between',
    marginTop: 10,
  },

  categoryCard: {
    width: '31%',       // 3 columns
    padding: 14,
    marginBottom: 12,
    borderRadius: 10,
    borderWidth: 1,
    borderColor: '#DDD',
    backgroundColor: '#FFF',
    alignItems: 'center',
  },

  categoryCardSelected: {
    backgroundColor: '#E3F2FD',
    borderColor: '#2196F3',
  },

  categoryText: {
    fontSize: 14,
    color: '#333',
    fontWeight: '500',
    textAlign: 'center',
  },

  categoryTextSelected: {
    color: '#2196F3',
    fontWeight: '700',
  },
  modalOverlay: {
    position: 'absolute',
    top: 0,
    left: 0,
    right: 0,
    bottom: 0,
    backgroundColor: 'rgba(0,0,0,0.4)',
    justifyContent: 'center',
    alignItems: 'center',
  },

  modalBox: {
    width: '90%',
    backgroundColor: '#FFF',
    borderRadius: 12,
    padding: 16,
  },

  modalTitle: {
    fontSize: 16,
    fontWeight: '700',
    marginBottom: 12,
  },

  productRow: {
    flexDirection: 'row',
    alignItems: 'center',
    paddingVertical: 10,
  },

  productText: {
    marginLeft: 10,
    fontSize: 14,
  },

  modalActions: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    marginTop: 16,
  },

  okBtn: {
    backgroundColor: '#2196F3',
    paddingVertical: 10,
    paddingHorizontal: 20,
    borderRadius: 8,
  },

  popupOverlay: {
    flex: 1,
    backgroundColor: 'rgba(0,0,0,0.35)',
    alignItems: 'center',
    justifyContent: 'center',
    padding: 24,
  },
  popupCard: {
    width: '100%',
    maxWidth: 360,
    backgroundColor: '#FFFFFF',
    borderRadius: 12,
    padding: 20,
    borderWidth: 1,
    borderColor: '#E6E6E6',
    shadowColor: '#000',
    shadowOpacity: 0.1,
    shadowRadius: 8,
    shadowOffset: { width: 0, height: 3 },
    elevation: 3,
  },
  popupTitle: {
    fontSize: 18,
    fontWeight: '700',
    color: '#1A1A1A',
    marginBottom: 8,
  },
  popupMessage: {
    fontSize: 14,
    color: '#444444',
    marginBottom: 16,
  },
  popupButton: {
    alignSelf: 'flex-end',
    backgroundColor: '#FF8A00',
    paddingHorizontal: 18,
    paddingVertical: 10,
    borderRadius: 8,
  },
  popupButtonText: {
    color: '#FFFFFF',
    fontWeight: '600',
    fontSize: 14,
  },

  // Business Timings section
  sectionHeader: {
    flexDirection: 'row',
    alignItems: 'center',
    marginBottom: 12,
    marginTop: 8,
    paddingBottom: 8,
    borderBottomWidth: 1,
    borderBottomColor: '#EEE',
  },
  sectionTitle: {
    fontSize: 16,
    fontWeight: '700',
    color: '#333',
    marginLeft: 8,
  },
  timeRow: {
    flexDirection: 'row',
    gap: 12,
    marginBottom: 16,
  },
  timeField: {
    flex: 1,
  },
  timePickerBtn: {
    flexDirection: 'row',
    alignItems: 'center',
    backgroundColor: '#FFF',
    borderWidth: 1,
    borderColor: '#DDD',
    borderRadius: 8,
    padding: 12,
    gap: 8,
  },
  timePickerText: {
    fontSize: 14,
    color: '#333',
  },
  dayChipsContainer: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    gap: 8,
  },
  dayChip: {
    paddingHorizontal: 14,
    paddingVertical: 8,
    borderRadius: 20,
    borderWidth: 1,
    borderColor: '#DDD',
    backgroundColor: '#FFF',
  },
  dayChipSelected: {
    backgroundColor: '#FF8A00',
    borderColor: '#FF8A00',
  },
  dayChipText: {
    fontSize: 13,
    fontWeight: '600',
    color: '#555',
  },
  dayChipTextSelected: {
    color: '#FFF',
  },
  timePickerRow: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    marginBottom: 16,
    gap: 8,
  },
  timeColumn: {
    flex: 1,
    alignItems: 'center',
  },
  timeColumnLabel: {
    fontSize: 12,
    fontWeight: '600',
    color: '#888',
    marginBottom: 8,
  },
  timeGrid: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    gap: 8,
  },
  timeGridItem: {
    width: '22%',
    paddingVertical: 10,
    borderRadius: 8,
    alignItems: 'center',
    backgroundColor: '#F5F5F5',
  },
  timeScroll: {
    maxHeight: 160,
  },
  timeOption: {
    paddingVertical: 8,
    paddingHorizontal: 14,
    borderRadius: 8,
    marginBottom: 4,
    alignItems: 'center',
    backgroundColor: '#F5F5F5',
  },
  timeOptionSelected: {
    backgroundColor: '#FF8A00',
  },
  timeOptionText: {
    fontSize: 16,
    fontWeight: '600',
    color: '#333',
  },
  timeOptionTextSelected: {
    color: '#FFF',
  },

  // Spinner Picker Styles
  wheelPickerCard: {
    width: '85%',
    maxWidth: 320,
    backgroundColor: '#FFFFFF',
    borderRadius: 16,
    padding: 24,
    shadowColor: '#000',
    shadowOpacity: 0.15,
    shadowRadius: 12,
    shadowOffset: { width: 0, height: 4 },
    elevation: 8,
  },
  wheelPickerTitle: {
    fontSize: 18,
    fontWeight: '700',
    color: '#1A1A1A',
    textAlign: 'center',
    marginBottom: 20,
  },
  wheelRow: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
  },
  spinnerColumn: {
    alignItems: 'center',
    flex: 1,
  },
  spinnerArrow: {
    padding: 8,
    alignItems: 'center',
    justifyContent: 'center',
  },
  spinnerValueBox: {
    borderWidth: 1,
    borderColor: '#DDD',
    borderRadius: 10,
    paddingVertical: 12,
    paddingHorizontal: 16,
    minWidth: 64,
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: '#FAFAFA',
    marginVertical: 4,
  },
  spinnerValue: {
    fontSize: 24,
    fontWeight: '700',
    color: '#1A1A1A',
  },
  wheelColon: {
    fontSize: 24,
    fontWeight: '700',
    color: '#1A1A1A',
    marginHorizontal: 2,
  },
  wheelActions: {
    flexDirection: 'row',
    justifyContent: 'flex-end',
    alignItems: 'center',
    marginTop: 24,
    gap: 16,
  },
  wheelCancelBtn: {
    paddingVertical: 10,
    paddingHorizontal: 20,
  },
  wheelCancelText: {
    fontSize: 16,
    fontWeight: '600',
    color: '#666',
  },
  wheelSaveBtn: {
    paddingVertical: 10,
    paddingHorizontal: 24,
    borderRadius: 8,
    borderWidth: 1,
    borderColor: '#DDD',
  },
  wheelSaveText: {
    fontSize: 16,
    fontWeight: '700',
    color: '#1A1A1A',
  },

  // Joining Fee section
  feeCard: {
    backgroundColor: '#FFF',
    borderRadius: 12,
    padding: 16,
    borderWidth: 1,
    borderColor: '#F0E0C7',
    marginBottom: 12,
  },
  feeRow: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    marginBottom: 6,
  },
  feeLabel: {
    fontSize: 15,
    fontWeight: '700',
    color: '#1A1A1A',
  },
  feeAmount: {
    fontSize: 20,
    fontWeight: '800',
    color: '#FF8A00',
  },
  feeSubText: {
    fontSize: 12,
    color: '#666',
    marginBottom: 12,
  },
  feeHint: {
    fontSize: 12,
    color: '#888',
    marginTop: 10,
    fontStyle: 'italic',
  },
  payFeeBtn: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    gap: 8,
    backgroundColor: '#FF8A00',
    paddingVertical: 14,
    borderRadius: 10,
  },
  payFeeBtnDisabled: {
    backgroundColor: '#CCCCCC',
  },
  payFeeBtnText: {
    color: '#FFFFFF',
    fontSize: 15,
    fontWeight: '700',
  },
  paymentReceivedBanner: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 8,
    backgroundColor: '#E8F5E9',
    borderRadius: 10,
    paddingVertical: 12,
    paddingHorizontal: 12,
    borderWidth: 1,
    borderColor: '#B7E1BF',
  },
  paymentReceivedText: {
    color: '#0C8A4A',
    fontSize: 14,
    fontWeight: '700',
  },
  paymentErrorBanner: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 8,
    backgroundColor: '#FDECEA',
    borderRadius: 10,
    paddingVertical: 10,
    paddingHorizontal: 12,
    borderWidth: 1,
    borderColor: '#F5C2C0',
    marginTop: 10,
  },
  paymentErrorText: {
    color: '#D32F2F',
    fontSize: 13,
    fontWeight: '600',
    flex: 1,
  },
});
